import React from 'react';

import Member from '../../components/member/member.component';
import CustomTitle from '../../components/custom-title/custom-title.component';
import AboutNav from '../../components/about-nav/about-nav.component';

import './team.styles.scss';

const Team = () => (
  <div className='team'>
    <AboutNav />
    <CustomTitle>Our Team</CustomTitle>
    <Member color="grey" image='https://static.wixstatic.com/media/140193_2993a2656383430fb4536fa7219f483d~mv2.jpg/v1/fill/w_273,h_271,al_c,q_80,usm_0.66_1.00_0.01/IMG_20180512_214951_308__01%20(1).webp' name="Wellford Dillard" title="Chief Executive Officer" description="I'm an eighteen-year-old gap year student from Lucknow, India. I’ve recently completed high school where I studied History, Political Science, Economics, and Mathematics. I’m a very curious person and love to know about the stories of different people, their culture and history, and how things work in our modern world. So, if you’re someone interested in discussing either of these fields or wish to contact me for any work/non-work related queries, feel free to reach out to my email address: yashvardhan.sharma2015@gmail.com" />
    <Member name="Wellford Dillard" image='https://static.wixstatic.com/media/140193_2993a2656383430fb4536fa7219f483d~mv2.jpg/v1/fill/w_273,h_271,al_c,q_80,usm_0.66_1.00_0.01/IMG_20180512_214951_308__01%20(1).webp' title="Chief Executive Officer" description='Wellford Dillard is the CEO of CM Group. Wellford has more than 15 years of experience in the software industry and held CFO roles at six companies prior to CM Group, including OPower (OPWR: sold to Oracle) and GetWellNetwork (sold to Welsh, Carson, Anderson and Stowe). Prior to holding senior leadership positions in the software industry, Wellford worked in management consulting, investment banking and equity research. Wellford holds an MBA from the University of Maryland and earned his BA in Finance from the University of Memphis.' />
    <Member color="grey" image='https://static.wixstatic.com/media/140193_2993a2656383430fb4536fa7219f483d~mv2.jpg/v1/fill/w_273,h_271,al_c,q_80,usm_0.66_1.00_0.01/IMG_20180512_214951_308__01%20(1).webp' name="Wellford Dillard" title="Chief Executive Officer" description='Wellford Dillard is the CEO of CM Group. Wellford has more than 15 years of experience in the software industry and held CFO roles at six companies prior to CM Group, including OPower (OPWR: sold to Oracle) and GetWellNetwork (sold to Welsh, Carson, Anderson and Stowe). Prior to holding senior leadership positions in the software industry, Wellford worked in management consulting, investment banking and equity research. Wellford holds an MBA from the University of Maryland and earned his BA in Finance from the University of Memphis.' />
    <Member name="Wellford Dillard" image='https://static.wixstatic.com/media/140193_2993a2656383430fb4536fa7219f483d~mv2.jpg/v1/fill/w_273,h_271,al_c,q_80,usm_0.66_1.00_0.01/IMG_20180512_214951_308__01%20(1).webp' title="Chief Executive Officer" description='Wellford Dillard is the CEO of CM Group. Wellford has more than 15 years of experience in the software industry and held CFO roles at six companies prior to CM Group, including OPower (OPWR: sold to Oracle) and GetWellNetwork (sold to Welsh, Carson, Anderson and Stowe). Prior to holding senior leadership positions in the software industry, Wellford worked in management consulting, investment banking and equity research. Wellford holds an MBA from the University of Maryland and earned his BA in Finance from the University of Memphis.' />
    <Member color="grey" image='https://static.wixstatic.com/media/140193_2993a2656383430fb4536fa7219f483d~mv2.jpg/v1/fill/w_273,h_271,al_c,q_80,usm_0.66_1.00_0.01/IMG_20180512_214951_308__01%20(1).webp' name="Wellford Dillard" title="Chief Executive Officer" description='Wellford Dillard is the CEO of CM Group. Wellford has more than 15 years of experience in the software industry and held CFO roles at six companies prior to CM Group, including OPower (OPWR: sold to Oracle) and GetWellNetwork (sold to Welsh, Carson, Anderson and Stowe). Prior to holding senior leadership positions in the software industry, Wellford worked in management consulting, investment banking and equity research. Wellford holds an MBA from the University of Maryland and earned his BA in Finance from the University of Memphis.' />
    <Member name="Wellford Dillard" image='https://static.wixstatic.com/media/140193_2993a2656383430fb4536fa7219f483d~mv2.jpg/v1/fill/w_273,h_271,al_c,q_80,usm_0.66_1.00_0.01/IMG_20180512_214951_308__01%20(1).webp' title="Chief Executive Officer" description='Wellford Dillard is the CEO of CM Group. Wellford has more than 15 years of experience in the software industry and held CFO roles at six companies prior to CM Group, including OPower (OPWR: sold to Oracle) and GetWellNetwork (sold to Welsh, Carson, Anderson and Stowe). Prior to holding senior leadership positions in the software industry, Wellford worked in management consulting, investment banking and equity research. Wellford holds an MBA from the University of Maryland and earned his BA in Finance from the University of Memphis.' />
  </div>
);

export default Team;